[tool.poetry]
name = "questionnaire-backend"
version = "0.1.0"
description = ""
authors = ["ph4nt0mm <100.ac@mail.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
